version: '3.9'
services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: 
      - 9200:9200
    volumes: 
      - ./data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports: 
     - 5601:5601